# Exercices sur les nombres

In [10]:
import random
from drawdata import ScatterWidget, BarWidget


widget = ScatterWidget()
widget

In [11]:
df = widget.data_as_pandas
df

Empty DataFrame
Columns: []
Index: []

In [12]:
barplot = bar.data_as_pandas
barplot

     collection  value  bin    color
0   collection1  0.000    0  #36A2EB
1   collection1  0.318    1  #36A2EB
2   collection1  0.770    2  #36A2EB
3   collection1  0.796    3  #36A2EB
4   collection1  0.000    4  #36A2EB
5   collection1  0.000    5  #36A2EB
6   collection1  0.000    6  #36A2EB
7   collection1  0.000    7  #36A2EB
8   collection1  0.000    8  #36A2EB
9   collection1  0.000    9  #36A2EB
10  collection1  0.000   10  #36A2EB
11  collection1  0.000   11  #36A2EB
12  collection1  0.000   12  #36A2EB
13  collection1  0.000   13  #36A2EB
14  collection1  0.000   14  #36A2EB
15  collection1  0.000   15  #36A2EB
16  collection1  0.000   16  #36A2EB
17  collection1  0.000   17  #36A2EB
18  collection1  0.000   18  #36A2EB
19  collection1  0.000   19  #36A2EB
20  collection1  0.000   20  #36A2EB
21  collection1  0.000   21  #36A2EB
22  collection1  0.000   22  #36A2EB
23  collection1  0.000   23  #36A2EB
24  collection2  0.000    0  #FFCE56
25  collection2  0.000    1  #FFCE56
26  collection2  0.000    2  #FFCE56
27  collection2  0.000    3  #FFCE56
28  collection2  0.766    4  #FFCE56
29  collection2  0.398    5  #FFCE56
30  collection2  0.086    6  #FFCE56
31  collection2  0.018    7  #FFCE56
32  collection2  0.000    8  #FFCE56
33  collection2  0.000    9  #FFCE56
34  collection2  0.000   10  #FFCE56
35  collection2  0.000   11  #FFCE56
36  collection2  0.000   12  #FFCE56
37  collection2  0.000   13  #FFCE56
38  collection2  0.000   14  #FFCE56
39  collection2  0.000   15  #FFCE56
40  collection2  0.000   16  #FFCE56
41  collection2  0.000   17  #FFCE56
42  collection2  0.000   18  #FFCE56
43  collection2  0.000   19  #FFCE56
44  collection2  0.000   20  #FFCE56
45  collection2  0.000   21  #FFCE56
46  collection2  0.000   22  #FFCE56
47  collection2  0.000   23  #FFCE56

## Exercice puissance
Soit $a$ un entier relatif et $n$ un entier naturel. On définit la puissance $a^n$
par récurrence de la façon suivante :

$$
\left \{
    \begin{array}{ll}
        a^n = 1 & \mbox{si } n=0 \\
        a^n = a.a^{n-1} & \mbox{sinon.}
    \end{array}
\right.
$$

Écrire la fonction récursive $puissance$ qui accepte en paramètres
un entier relatif $a$ et un entier naturel $n$ et retourne
le résultat du calcul de $a**n$.

In [2]:
def puissance(a, n):
    if n == 0: # cas d'arret
        return 1
    elif n < 0:
        return 1 / puissance(a, -n)
    else:
        return a * puissance(a, n - 1)
    
print(puissance(2, 3))
print(puissance(2, -3)) 
print(puissance(1, -3))

8
0.125
1.0

## Exercice somme chiffres
Écrire la fonction récursive $somme\_chiffres$ qui accepte en paramètre
un entier naturel $n$ et retourne la somme des chiffres *(en base 10)*
de $n$.

In [3]:
def somme_chiffres(n):
    if n == 0: # cas d'arret
        return 0
    return n % 10 + somme_chiffres(n//10)

print(somme_chiffres(56655))

27

# Exercices sur les listes

## Définition du type liste

In [4]:
def creer_liste_vide():
    return None

def creer_liste(t,q):
    return t,q

def tete(liste):
    return liste[0]

def queue(liste):
    return liste[1]

def est_vide(liste):
    return liste==None

## Exercice longueur liste
Écrire la fonction récursive $longueur$ qui retourne le nombre
d'éléments d'une liste chaînée.

In [5]:
liste0 = creer_liste_vide()
liste1 = creer_liste(13,liste0)
liste2 = creer_liste(21,liste1)
liste3 = creer_liste(8,liste2)

In [6]:
def longueur(liste):
    if est_vide(liste):
        return 0 
    else:
        return 1 + longueur(queue(liste))

print(longueur(liste3))

3

## Exercice substitution première occurence
Écrire la fonction récursive $substituer\_premiere\_occurence$ qui accepte
en paramètres :

*   une liste chaînée d'entiers $liste$,
*   un entier $ancienne\_valeur$,
*   un entier $nouvelle\_valeur$.

La fonction retourne une nouvelle liste dans laquelle la première occurrence de
$ancienne\_valeur$ est remplacée par $nouvelle\_valeur$.

In [10]:
def substituer_premiere_occurence(liste, x, y):
    if est_vide(liste):
        return creer_liste_vide()
    elif tete(liste) == x:
        return creer_liste(y, queue(liste))
    else:
        return creer_liste(tete(liste), substituer_premiere_occurence(queue(liste), x, y))
    
print(liste3)
print(substituer_premiere_occurence(liste3, 1, 42))

(8, (21, (13, None)))
(8, (21, (13, None)))

Select sort avec liste chainées

In [46]:
a = 5
a

5

In [52]:
def generer_liste_chaine(n):
    x = random.randint(1,1000)
    if n == 0:
        return creer_liste_vide()
    else:
        return creer_liste(x, generer_liste_chaine(n-1))

liste_genere = generer_liste_chaine(802)

In [57]:
def concatener(liste1, liste2):
    if est_vide(liste1): # cas d'arret
        return liste2
    else:
        return creer_liste(tete(liste1), concatener(queue(liste1), liste2)) # concatener le reste de liste1 avec liste2 et ajouter tete(liste1) au debut

def quick_sort_liste_chainées(liste):
    """quick sort pour les listes chainées"""
    if est_vide(liste) or est_vide(queue(liste)):
        return liste

    pivot = tete(liste) # choisir le pivot comme le premier élément de la liste
    reste = queue(liste)

    inf,sup = partition(reste,pivot) # partitionner le reste de la liste en deux listes: inf et sup

    return concatener(
        quick_sort_liste_chainées(inf),
        creer_liste(pivot,
        quick_sort_liste_chainées(sup))) # trier les deux listes inf et sup récursivement et concatener les résultats avec le pivot au milieu


def partition(liste,pivot):
    """partitionne la liste en deux listes: inf et sup"""
    inf = creer_liste_vide()
    sup = creer_liste_vide()


    while not est_vide(liste): # tant que liste pas vide 
        if tete(liste) < pivot: # mettre tete devant inf
            inf = creer_liste(tete(liste),inf)
        else:
            sup = creer_liste(tete(liste),sup)  # mettre tete devant inf
        liste = queue(liste) # mettre a jour liste retirer tete pour pas avoir de RecusrionError
    return inf,sup

print(quick_sort_liste_chainées(liste_genere))

(2, (3, (3, (4, (5, (6, (9, (9, (11, (11, (12, (12, (15, (17, (17, (17, (19, (20, (20, (20, (21, (21, (22, (24, (26, (26, (27, (28, (28, (29, (30, (34, (35, (36, (37, (38, (38, (39, (40, (40, (41, (43, (43, (46, (48, (52, (52, (53, (54, (55, (56, (56, (61, (63, (64, (66, (67, (67, (68, (69, (73, (77, (78, (80, (80, (81, (82, (82, (83, (83, (85, (85, (87, (87, (91, (91, (93, (94, (94, (96, (96, (97, (100, (101, (104, (105, (106, (108, (113, (113, (114, (114, (115, (115, (117, (117, (119, (119, (121, (121, (123, (127, (129, (131, (131, (131, (132, (134, (134, (134, (135, (136, (138, (138, (139, (141, (141, (143, (143, (144, (144, (146, (146, (147, (148, (150, (153, (154, (155, (155, (156, (156, (160, (165, (166, (167, (167, (168, (170, (170, (171, (172, (172, (172, (173, (174, (175, (175, (179, (180, (182, (184, (184, (187, (189, (189, (192, (192, (197, (197, (202, (202, (204, (204, (205, (209, (209, (209, (209, (209, (210, (211, (214, (214, (214, (215, (217, (218, (219, (220, (221, (222, (224, (225, (228, (231, (232, (232, (235, (236, (236, (237, (238, (238, (238, (238, (241, (242, (242, (244, (245, (247, (247, (248, (252, (255, (256, (257, (261, (261, (265, (269, (271, (272, (272, (272, (275, (276, (283, (284, (285, (288, (289, (290, (291, (291, (291, (292, (292, (292, (293, (294, (296, (299, (299, (299, (300, (304, (305, (305, (306, (308, (312, (315, (316, (318, (319, (323, (324, (325, (326, (326, (329, (330, (331, (332, (334, (334, (336, (338, (339, (340, (340, (342, (342, (346, (346, (348, (349, (350, (351, (352, (355, (355, (355, (357, (359, (360, (363, (364, (367, (370, (370, (372, (373, (374, (374, (375, (377, (377, (380, (381, (386, (386, (388, (389, (392, (392, (393, (394, (394, (395, (395, (399, (401, (403, (404, (407, (408, (409, (410, (411, (411, (412, (413, (414, (414, (415, (419, (419, (419, (420, (422, (424, (426, (426, (428, (429, (430, (432, (434, (436, (438, (442, (443, (444, (445, (446, (446, (447, (447, (447, (447, (448, (452, (452, (455, (457, (457, (458, (460, (460, (460, (460, (460, (463, (464, (464, (465, (466, (466, (467, (470, (473, (473, (477, (479, (480, (481, (481, (482, (482, (483, (484, (484, (487, (487, (490, (493, (493, (495, (496, (499, (499, (501, (506, (506, (506, (507, (509, (509, (510, (510, (510, (510, (510, (510, (511, (511, (511, (512, (515, (516, (518, (520, (522, (529, (532, (533, (534, (535, (536, (537, (538, (542, (544, (546, (550, (550, (551, (553, (554, (554, (554, (555, (556, (557, (557, (562, (565, (568, (568, (568, (569, (569, (573, (574, (575, (579, (583, (585, (588, (588, (589, (590, (590, (592, (594, (594, (595, (595, (595, (596, (598, (601, (601, (601, (603, (603, (607, (608, (608, (610, (610, (612, (612, (612, (613, (613, (613, (614, (615, (615, (616, (619, (619, (620, (622, (623, (624, (626, (628, (628, (629, (631, (632, (632, (634, (635, (635, (636, (641, (642, (642, (642, (643, (648, (649, (651, (652, (652, (653, (653, (653, (653, (654, (656, (656, (658, (659, (661, (663, (663, (663, (663, (663, (664, (664, (666, (666, (668, (669, (670, (673, (674, (674, (676, (679, (682, (684, (684, (685, (685, (687, (687, (689, (689, (691, (691, (693, (694, (695, (695, (696, (696, (702, (702, (703, (703, (704, (704, (706, (708, (710, (711, (712, (713, (713, (713, (713, (714, (715, (715, (717, (717, (718, (719, (719, (719, (720, (722, (724, (725, (727, (728, (728, (729, (730, (732, (734, (734, (735, (735, (735, (736, (737, (737, (740, (742, (742, (743, (743, (743, (745, (746, (747, (748, (748, (749, (751, (751, (752, (753, (754, (755, (756, (756, (758, (758, (759, (760, (760, (760, (767, (768, (769, (770, (774, (776, (777, (778, (779, (780, (781, (781, (782, (783, (783, (784, (785, (786, (786, (787, (787, (788, (788, (789, (789, (790, (792, (794, (798, (798, (799, (803, (803, (805, (805, (806, (806, (809, (809, (810, (815, (816, (816, (817, (817, (817, (817, (819, (820, (821, (823, (825, (827, (828, (829, (830, (831, (831, (832, (835, (836, (839, (839, (839, (841, (841, (841, (843, (846, (848, (849, (850, (850, (851, (853, (854, (856, (857, (859, (865, (865, (866, (866, (867, (868, (870, (875, (876, (877, (877, (877, (878, (879, (880, (882, (882, (883, (885, (885, (888, (889, (891, (892, (894, (895, (897, (898, (900, (903, (903, (906, (907, (907, (909, (910, (911, (911, (912, (912, (915, (917, (919, (920, (920, (921, (924, (925, (926, (928, (929, (929, (930, (930, (931, (932, (933, (934, (937, (939, (940, (942, (944, (945, (945, (945, (947, (949, (950, (952, (954, (955, (956, (956, (956, (958, (960, (966, (968, (968, (969, (969, (972, (973, (974, (975, (975, (976, (976, (977, (978, (979, (980, (981, (983, (983, (985, (986, (987, (988, (990, (991, (994, (994, (994, (997, (998, (998, (998, (999, None))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))