# Exercices sur les nombres

In [2]:
import random
from drawdata import ScatterWidget, BarWidget


widget = ScatterWidget()
widget

In [3]:
df = widget.data_as_pandas
df

Empty DataFrame
Columns: []
Index: []

In [4]:
bar = BarWidget()
bar

In [5]:
barplot = bar.data_as_pandas
barplot

Empty DataFrame
Columns: []
Index: []

## Exercice puissance
Soit $a$ un entier relatif et $n$ un entier naturel. On définit la puissance $a^n$
par récurrence de la façon suivante :

$$
\left \{
    \begin{array}{ll}
        a^n = 1 & \mbox{si } n=0 \\
        a^n = a.a^{n-1} & \mbox{sinon.}
    \end{array}
\right.
$$

Écrire la fonction récursive $puissance$ qui accepte en paramètres
un entier relatif $a$ et un entier naturel $n$ et retourne
le résultat du calcul de $a**n$.

In [6]:
def puissance(a, n):
    if n == 0: # cas d'arret
        return 1
    elif n < 0:
        return 1 / puissance(a, -n)
    else:
        return a * puissance(a, n - 1)
    
print(puissance(2, 3))
print(puissance(2, -3)) 
print(puissance(1, -3))

8
0.125
1.0

## Exercice somme chiffres
Écrire la fonction récursive $somme\_chiffres$ qui accepte en paramètre
un entier naturel $n$ et retourne la somme des chiffres *(en base 10)*
de $n$.

In [7]:
def somme_chiffres(n):
    if n == 0: # cas d'arret
        return 0
    return n % 10 + somme_chiffres(n//10)

print(somme_chiffres(56655))

27

# Exercices sur les listes

## Définition du type liste

In [8]:
def creer_liste_vide():
    return None

def creer_liste(t,q):
    return t,q

def tete(liste):
    return liste[0]

def queue(liste):
    return liste[1]

def est_vide(liste):
    return liste==None

## Exercice longueur liste
Écrire la fonction récursive $longueur$ qui retourne le nombre
d'éléments d'une liste chaînée.

In [9]:
liste0 = creer_liste_vide()
liste1 = creer_liste(13,liste0)
liste2 = creer_liste(21,liste1)
liste3 = creer_liste(8,liste2)

In [10]:
def longueur(liste):
    if est_vide(liste):
        return 0 
    else:
        return 1 + longueur(queue(liste))

print(longueur(liste3))

3

## Exercice substitution première occurence
Écrire la fonction récursive $substituer\_premiere\_occurence$ qui accepte
en paramètres :

*   une liste chaînée d'entiers $liste$,
*   un entier $ancienne\_valeur$,
*   un entier $nouvelle\_valeur$.

La fonction retourne une nouvelle liste dans laquelle la première occurrence de
$ancienne\_valeur$ est remplacée par $nouvelle\_valeur$.

In [11]:
def substituer_premiere_occurence(liste, x, y):
    if est_vide(liste):
        return creer_liste_vide()
    elif tete(liste) == x:
        return creer_liste(y, queue(liste))
    else:
        return creer_liste(tete(liste), substituer_premiere_occurence(queue(liste), x, y))
    
print(liste3)
print(substituer_premiere_occurence(liste3, 1, 42))

(8, (21, (13, None)))
(8, (21, (13, None)))

Select sort avec liste chainées

In [12]:
a = 5
a

5

In [26]:
def generer_liste_chaine(n):
    return creer_liste_vide() if n == 0 else creer_liste(random.randint(1,1000), generer_liste_chaine(n-1))

liste_genere = generer_liste_chaine(802)

In [ ]:
def concatener(liste1, liste2):
    if est_vide(liste1): # cas d'arret
        return liste2
    else:
        return creer_liste(tete(liste1), concatener(queue(liste1), liste2)) # concatener le reste de liste1 avec liste2 et ajouter tete(liste1) au debut

def quick_sort_liste_chainées(liste):
    """quick sort pour les listes chainées"""
    if est_vide(liste) or est_vide(queue(liste)):
        return liste

    pivot = tete(liste) # choisir le pivot comme le premier élément de la liste
    reste = queue(liste)

    inf,sup = partition(reste,pivot) # partitionner le reste de la liste en deux listes: inf et sup

    return concatener(
        quick_sort_liste_chainées(inf),
        creer_liste(pivot,
        quick_sort_liste_chainées(sup))) # trier les deux listes inf et sup récursivement et concatener les résultats avec le pivot au milieu


def partition(liste,pivot):
    """partitionne la liste en deux listes: inf et sup"""
    inf = creer_liste_vide()
    sup = creer_liste_vide()


    while not est_vide(liste): # tant que liste pas vide 
        if tete(liste) < pivot: # mettre tete devant inf
            inf = creer_liste(tete(liste),inf)
        else:
            sup = creer_liste(tete(liste),sup)  # mettre tete devant inf
        liste = queue(liste) # mettre a jour liste retirer tete pour pas avoir de RecusrionError (retirer tete en garder le reste de la liste)
    return inf,sup

print(quick_sort_liste_chainées(liste_genere))

(1, (4, (5, (6, (10, (10, (13, (16, (18, (18, (18, (19, (20, (20, (20, (26, (26, (29, (34, (37, (39, (39, (39, (41, (41, (42, (43, (46, (48, (49, (51, (51, (52, (52, (53, (53, (53, (54, (55, (55, (55, (56, (57, (57, (57, (58, (58, (58, (61, (61, (63, (65, (66, (70, (71, (73, (73, (74, (75, (75, (77, (78, (80, (80, (80, (80, (81, (82, (83, (84, (85, (86, (86, (88, (89, (92, (94, (94, (99, (100, (101, (101, (102, (103, (108, (110, (115, (115, (117, (117, (120, (120, (120, (120, (121, (122, (123, (124, (124, (124, (124, (124, (126, (126, (127, (128, (129, (129, (130, (130, (135, (136, (137, (137, (141, (141, (142, (143, (147, (147, (147, (148, (148, (149, (149, (156, (157, (158, (159, (159, (160, (162, (163, (164, (166, (171, (180, (183, (183, (183, (184, (184, (185, (185, (189, (191, (192, (192, (195, (197, (201, (201, (201, (202, (208, (210, (214, (215, (217, (217, (218, (218, (219, (220, (220, (222, (223, (224, (224, (225, (225, (226, (229, (230, (233, (236, (236, (237, (239, (239, (240, (240, (241, (242, (243, (243, (243, (244, (246, (247, (253, (254, (254, (254, (256, (257, (258, (259, (261, (262, (263, (263, (263, (268, (269, (270, (273, (283, (284, (284, (285, (286, (286, (289, (290, (290, (292, (294, (296, (299, (301, (301, (302, (302, (304, (304, (306, (306, (307, (309, (310, (311, (312, (315, (321, (326, (327, (328, (328, (329, (330, (332, (334, (334, (334, (335, (335, (337, (339, (341, (342, (343, (346, (348, (348, (349, (350, (352, (353, (354, (354, (355, (355, (355, (355, (355, (356, (357, (362, (363, (363, (367, (368, (368, (371, (372, (373, (373, (373, (376, (376, (378, (382, (382, (382, (384, (384, (385, (389, (392, (393, (395, (395, (395, (397, (398, (402, (404, (405, (406, (408, (409, (409, (411, (412, (413, (414, (414, (414, (415, (417, (423, (424, (425, (426, (426, (431, (431, (433, (434, (435, (437, (438, (438, (439, (440, (441, (443, (445, (446, (450, (452, (453, (458, (458, (460, (464, (465, (465, (465, (467, (468, (468, (469, (470, (472, (473, (473, (474, (474, (475, (476, (477, (477, (478, (478, (478, (479, (480, (480, (482, (483, (485, (485, (485, (486, (487, (487, (487, (490, (492, (493, (494, (494, (496, (496, (497, (498, (498, (500, (501, (501, (502, (505, (507, (507, (510, (511, (512, (513, (513, (514, (514, (516, (520, (520, (521, (521, (522, (522, (522, (524, (525, (527, (528, (528, (530, (531, (532, (534, (534, (535, (537, (540, (541, (542, (545, (548, (548, (548, (551, (552, (556, (557, (559, (560, (560, (561, (562, (563, (564, (573, (574, (574, (574, (574, (575, (575, (576, (576, (577, (580, (581, (581, (581, (582, (583, (583, (587, (589, (590, (590, (590, (593, (598, (598, (600, (603, (608, (609, (609, (610, (610, (612, (612, (614, (616, (616, (616, (616, (617, (617, (618, (619, (620, (622, (624, (624, (626, (626, (629, (630, (630, (631, (632, (634, (635, (636, (637, (637, (637, (639, (640, (640, (642, (642, (643, (643, (644, (644, (645, (645, (645, (646, (648, (651, (653, (655, (656, (657, (657, (658, (658, (663, (663, (664, (665, (668, (672, (673, (674, (674, (675, (675, (677, (678, (678, (678, (679, (679, (679, (680, (680, (682, (683, (683, (683, (685, (686, (687, (689, (690, (691, (692, (692, (693, (701, (701, (704, (708, (710, (712, (713, (715, (717, (718, (719, (720, (721, (721, (722, (722, (723, (725, (726, (729, (729, (731, (731, (733, (733, (733, (734, (734, (735, (735, (737, (737, (738, (742, (743, (745, (746, (747, (747, (747, (747, (748, (748, (750, (750, (751, (751, (751, (754, (754, (755, (755, (757, (758, (758, (758, (759, (759, (760, (760, (760, (762, (764, (765, (766, (769, (769, (771, (771, (771, (771, (772, (773, (777, (778, (778, (780, (780, (780, (781, (782, (782, (787, (790, (791, (793, (797, (798, (803, (804, (805, (806, (806, (807, (807, (808, (808, (808, (808, (808, (809, (809, (809, (810, (811, (811, (811, (812, (814, (815, (816, (817, (818, (818, (820, (821, (822, (822, (823, (825, (826, (826, (828, (828, (829, (829, (829, (830, (832, (832, (833, (834, (834, (836, (836, (836, (840, (844, (845, (845, (845, (849, (850, (853, (854, (855, (855, (860, (861, (862, (863, (864, (867, (868, (870, (872, (874, (876, (876, (878, (878, (878, (879, (880, (883, (883, (886, (887, (888, (888, (890, (894, (894, (896, (898, (901, (904, (904, (904, (907, (911, (911, (914, (914, (914, (915, (918, (919, (921, (921, (921, (923, (923, (926, (926, (928, (929, (929, (929, (931, (933, (933, (934, (934, (934, (938, (938, (940, (941, (943, (945, (946, (949, (949, (950, (951, (951, (951, (952, (952, (954, (955, (955, (957, (959, (959, (960, (962, (962, (963, (964, (965, (965, (966, (966, (968, (969, (970, (971, (972, (973, (973, (975, (975, (977, (977, (981, (982, (983, (990, (991, (993, (994, (998, (999, (1000, None))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))

TP ARBRE

La construction de l’arbre s’effectue de la manière suivante :
Le premier élément de cet ensemble (50) servira de racine à notre arbre,
- Les éléments suivants sont ensuite ajoutés par ordre d’apparition dans l’ensemble.
Pour ajouter une nouvelle valeur, on part de la racine de l’arbre, en considérant la racine comme
le nœud courant. On peut ajouter un élément au nœud courant, si
- l’élément à ajouter est strictement inférieur à l’élément du nœud courant
- si ce dernier n’a pas de fils gauche, on crée un nouveau nœud avec cette valeur
et on l’associe au fils gauche ;

- si le nœud courant a déjà un fils gauche, on essaye alors d’insérer cette nouvelle
valeur à partir du fils gauche ;
- l’élément à ajouter est supérieur à l’élément du nœud courant
- si ce dernier n’a pas de fils droit, on crée un nouveau nœud avec cette valeur
et on l’associe au fils droit ;
- si le nœud courant a déjà un fils droit, on essaye alors d’insérer cette nouvelle
valeur à partir du fils droit ;