<h1 style="color: indianred;text-align: center;">Using Pandas </h1>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [54]:
df = pd.read_csv("../data/Athletes_summer_games.csv")

df.head()

,Unnamed: 0,Name,Sex,Age,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,0,A Dijiang,M,24.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,1,A Lamusi,M,23.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,2,Gunnar Nielsen Aaby,M,24.0,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,3,Edgar Lindenau Aabye,M,34.0,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,26,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN

In [ ]:
df.dropna(inplace=True)
print(df.columns)
df.Age.astype(int).mean()

try:
    df.drop('Unnamed: 0',axis='columns',inplace=True)
except KeyError:
    print('Colonne pas présente.')

df.groupby('Team').describe()

Index(['Name', 'Sex', 'Age', 'Team', 'NOC', 'Games', 'Year', 'Season', 'City',
       'Sport', 'Event', 'Medal'],
      dtype='str')
Colonne pas présente.

                                Age                                           \
                              count       mean        std   min    25%   50%
Team
A North American Team           3.0  41.333333   3.055050  38.0  40.00  42.0
Afghanistan                     2.0  23.000000   2.828427  21.0  22.00  23.0
Algeria                        17.0  24.117647   2.758676  19.0  23.00  24.0
Ali-Baba II                     5.0  40.000000  12.227019  26.0  28.00  44.0
Amateur Athletic Association    5.0  24.600000   2.880972  22.0  23.00  23.0
...                             ...        ...        ...   ...    ...   ...
Winnipeg Shamrocks-1           12.0  26.250000   2.927146  22.0  24.75  25.5
Yugoslavia                    382.0  24.725131   3.643618  14.0  22.00  24.0
Zambia                          1.0  27.000000        NaN  27.0  27.00  27.0
Zimbabwe                       22.0  25.363636   4.123631  20.0  24.00  24.0
Zut                             3.0  32.000000   1.000000  31.0  31.50  32.0

                                           Year                          \
                               75%   max  count         mean        std
Team
A North American Team         43.0  44.0    3.0  1900.000000   0.000000
Afghanistan                   24.0  25.0    2.0  2010.000000   2.828427
Algeria                       26.0  29.0   17.0  2000.000000   9.591663
Ali-Baba II                   51.0  51.0    5.0  1948.000000   0.000000
Amateur Athletic Association  26.0  29.0    5.0  1900.000000   0.000000
...                            ...   ...    ...          ...        ...
Winnipeg Shamrocks-1          27.5  32.0   12.0  1904.000000   0.000000
Yugoslavia                    27.0  37.0  382.0  1972.774869  15.211082
Zambia                        27.0  27.0    1.0  1996.000000        NaN
Zimbabwe                      26.0  35.0   22.0  1988.363636  12.583229
Zut                           32.5  33.0    3.0  1908.000000   0.000000


                                 min     25%     50%     75%     max
Team
A North American Team         1900.0  1900.0  1900.0  1900.0  1900.0
Afghanistan                   2008.0  2009.0  2010.0  2011.0  2012.0
Algeria                       1984.0  1996.0  2000.0  2008.0  2016.0
Ali-Baba II                   1948.0  1948.0  1948.0  1948.0  1948.0
Amateur Athletic Association  1900.0  1900.0  1900.0  1900.0  1900.0
...                              ...     ...     ...     ...     ...
Winnipeg Shamrocks-1          1904.0  1904.0  1904.0  1904.0  1904.0
Yugoslavia                    1924.0  1964.0  1980.0  1984.0  1988.0
Zambia                        1996.0  1996.0  1996.0  1996.0  1996.0
Zimbabwe                      1980.0  1980.0  1980.0  2004.0  2008.0
Zut                           1908.0  1908.0  1908.0  1908.0  1908.0

[472 rows x 16 columns]

In [95]:
df_sport_team = df.groupby(['Team','Sport'])['Age'].mean() # series one dimension
df_sport_team = df.groupby(['Team','Sport'])[['Age']].mean() # df 
df_sport_team['x'] = df.groupby(['Team','Sport'])['Age'].mean() - 2000 # create a column

# When you run a groupby(['Team', 'Sport']), Pandas takes those two columns and moves them into the Index (the row labels). 
# They are no longer considered "Data Columns."
# So shape (...,1)

arbres = df.loc[df.Team.isin(['Algeria','Morocco'])]

l = list(set(df.Team))

if 'Algeria' in l:
    print(l.index('Algeria'))

633